export const letters = {
	a: "https://mowicpopolsku.com/wp-content/uploads/audio/1-a.mp3",
	b: "https://mowicpopolsku.com/wp-content/uploads/audio/5-b.mp3",
	c: "https://mowicpopolsku.com/wp-content/uploads/audio/7-c.mp3",
	d: "https://mowicpopolsku.com/wp-content/uploads/audio/11-d.mp3",
	e: "https://mowicpopolsku.com/wp-content/uploads/audio/13-e.mp3",
	f: "https://mowicpopolsku.com/wp-content/uploads/audio/17-f.mp3",
	g: "https://mowicpopolsku.com/wp-content/uploads/audio/19-g.mp3",
	h: "https://mowicpopolsku.com/wp-content/uploads/audio/21-h.mp3",
	i: "https://mowicpopolsku.com/wp-content/uploads/audio/23-i.mp3",
	j: "https://mowicpopolsku.com/wp-content/uploads/audio/25-j.mp3",
	k: "https://mowicpopolsku.com/wp-content/uploads/audio/27-k.mp3",
	l: "https://mowicpopolsku.com/wp-content/uploads/audio/29-l.mp3",
	m: "https://mowicpopolsku.com/wp-content/uploads/audio/33-m.mp3",
	n: "https://mowicpopolsku.com/wp-content/uploads/audio/35-n.mp3",
	o: "https://mowicpopolsku.com/wp-content/uploads/audio/39-o.mp3",
	p: "https://mowicpopolsku.com/wp-content/uploads/audio/43-p.mp3",
	r: "https://mowicpopolsku.com/wp-content/uploads/audio/45-r.mp3",
	s: "https://mowicpopolsku.com/wp-content/uploads/audio/47-s.mp3",
	t: "https://mowicpopolsku.com/wp-content/uploads/audio/51-t.mp3",
	u: "https://mowicpopolsku.com/wp-content/uploads/audio/53-u.mp3",
	w: "https://mowicpopolsku.com/wp-content/uploads/audio/55-w.mp3",
	y: "https://mowicpopolsku.com/wp-content/uploads/audio/57-y.mp3",
	z: "https://mowicpopolsku.com/wp-content/uploads/audio/59-z.mp3",
}
